<?php
function get_title_case($input) {
    $ignore = ["a", "an", "the", "and", "but", "or", "nor", "at", "by", "for", "from", "in", "into", "of", "off", "on", "onto", "out", "up", "with", "to", "as"];

    $input = explode(' ', $input);
    $final = [];
    foreach ($input as $word) {
        in_array($word, $ignore) ? array_push($final, $word) : array_push($final, ucfirst($word));
    }
    return implode(' ', $final);
}
